### PR TITLE
fix linux module insmod failure on kernel 6.12+

### LINKED ISSUE #7250: 编译linux ko insmod失败
### Xmake 版本

v3.0.6

### 操作系统版本和架构

windows wsl

### 描述问题

使用如下 xmake脚本编译ko
生成的ko insmod 失败，modinfo 信息如下
```
filename:       /home/csk/hardware_test/my_driver/build/linux/x86_64/debug/./pci_test.ko
description:    Driver for fake GPU PCI device
author:         You
license:        GPL
alias:          pci:v00001AF4d00001000sv*sd*bc*sc*i*
depends:        
name:           pci_test
srcversion:     533BB7E5866E52F63B9ACCB
depends:        
name:           pci_test
```
对比正常make 生成的ko丢失 如下信息
```
vermagic:       6.18.0 SMP preempt mod_unload
```

### 期待的结果

期待insmod ko 正常

### 工程配置

target("pci_test")
    add_rules("platform.linux.module")
    add_files("src/*.c")
    set_values("linux.driver.linux-headers", "/home/csk/hardware_test/linux_modules/lib/modules/6.18.0/build")
    add_cxflags("-O2")

### 附加信息和错误日志

xmake 编译没有出现错误

### PR DESCRIPTION
**Pull request by ririyeye**
## Summary
- fix the linux module rule for kernels that use `scripts/module-common.c` during the final module link step so generated `.ko` files keep the metadata required by modern kernels
- tighten kernel config detection and share `module-common.c` lookup between dependency tracking and compilation to address review follow-ups
- fix same-platform Linux cross compilation by passing `ARCH`/`CROSS_COMPILE` during kbuild flag probing and add a minimal cross-build driver example

## Problems found
- kernels that rely on `scripts/module-common.c` could lose vermagic and related metadata in the final module link step
- `_has_linux_headers_config()` could false-match config prefixes such as `CONFIG_FOO` vs `CONFIG_FOO_BAR`
- `module-common.c` path resolution was duplicated in two places, which could drift over time
- Linux cross builds on the same host platform but a different target arch did not pass `ARCH`/`CROSS_COMPILE` into the probing `make` invocation
- versioned gcc names such as `aarch64-linux-gnu-gcc-12` were not handled when deriving the `CROSS_COMPILE` prefix

## Fixes
- import kernel `Module.symvers`, preserve the required modpost flags, and compile/link `module-common.c` when present
- normalize config files and match options by exact line boundaries
- extract a shared helper for locating `module-common.c`
- map target arches to Linux kbuild arch names and pass `ARCH`/`CROSS_COMPILE` whenever the build is cross-platform or cross-arch
- derive the toolchain prefix from both plain and versioned gcc executable names
- add `tests/projects/linux/driver/hello_cross` as a minimal cross-compilation example using custom kernel headers/builddir settings

Fixes #7250

## Test plan
- [x] Build `tests/projects/linux/driver/hello_custom` for Linux 4.9 arm64 with `/opt/toolchain/7.5.0/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc`
- [x] Build `tests/projects/linux/driver/hello_custom` for Linux 5.10 arm with `/opt/linux/x86-arm/arm-v01c02-linux-musleabi-gcc/bin/arm-linux-musleabi-gcc`
- [x] Build `tests/projects/linux/driver/hello_cross` for Linux 4.9 arm64 with the same aarch64 cross toolchain
- [x] Build `tests/projects/linux/driver/hello_cross` for Linux 5.10 arm with the same arm cross toolchain
- [x] Confirm each build produced the expected `.ko` output

Made with [Cursor](https://cursor.com)

### CODE REVIEW

**Comment by waruqi** [comment]
Did you test it on kernel <6? Does it work too?

**Comment by ririyeye** [comment]
Thanks! I addressed the follow-up review comments in d84515c30.

Changes:
- tightened `_has_linux_headers_config()` to do exact line-based matches, so config prefixes won't produce false positives
- extracted a shared helper for resolving `module-common.c`, and reused it in both dependency tracking and compilation

I also validated the updated rule against two older kernel setups locally:
- Linux 4.9 (arm64, cross toolchain)
- Linux 5.10 (arm, cross toolchain)

Both builds completed successfully and produced the expected `.ko` output.

File: xmake/rules/platform/linux/module/driver_modules.lua [hunk 1]
```diff
@@ -25,6 +25,73 @@ import("core.cache.memcache")
...
+        return "mips"
+    elseif target:is_arch("ppc", "ppc64", "powerpc", "powerpc64") then
+        return "powerpc"
+    elseif target:is_arch("riscv64", "riscv32") then
+        return "riscv"
+    end
+end
+
+function _get_linux_cross_compile(target)
+    local cc = target:tool("cc")
```
Comment (waruqi) [inline xmake/rules/platform/linux/module/driver_modules.lua:51]: use `target:is_cross()`

File: xmake/rules/platform/linux/module/driver_modules.lua [hunk 2]
```diff
@@ -25,6 +25,73 @@ import("core.cache.memcache")
...
+    if cc then
+        return cc:match("^(.*%-)gcc[%-%d%.]*$")
+    end
+end
+
+function _get_linux_headers_modulecommon(linux_headers)
+    local builddir = _get_linux_headers_builddir(linux_headers)
+    local modulecommon = path.join(linux_headers.sdkdir, "scripts", "module-common.c")
+    if not os.isfile(modulecommon) and builddir ~= linux_headers.sdkdir then
```
Comment (waruqi) [inline xmake/rules/platform/linux/module/driver_modules.lua]: use path.normalize() before compare path and check nil path

File: xmake/rules/platform/linux/module/driver_modules.lua [hunk 3]
```diff
@@ -25,6 +25,73 @@ import("core.cache.memcache")
...
+        end
+        memcache.set2("linux.driver", key, "data", configdata or false)
+    end
+    return configdata or nil
+end
+
+function _has_linux_headers_config(linux_headers, config)
+    local configdata = _get_linux_headers_config(linux_headers)
+    if configdata then
+        local normalized = "\n" .. configdata:gsub("\r\n", "\n"):gsub("\r", "\n") .. "\n"
```
Comment (waruqi) [inline xmake/rules/platform/linux/module/driver_modules.lua]: use string split and check line

File: xmake/rules/platform/linux/module/driver_modules.lua [hunk 4]
```diff
@@ -87,9 +89,14 @@ end
 function _has_linux_headers_config(linux_headers, config)
     local configdata = _get_linux_headers_config(linux_headers)
     if configdata then
-        local normalized = "\n" .. configdata:gsub("\r\n", "\n"):gsub("\r", "\n") .. "\n"
-        return normalized:find("\n" .. config .. "=y\n", 1, true) or normalized:find("\n#define " .. config .. " 1\n", 1, true)
+        local normalized = configdata:gsub("\r\n", "\n"):gsub("\r", "\n")
```
Comment (waruqi) [inline xmake/rules/platform/linux/module/driver_modules.lua]: io read will convert to `\n`, we need not to do it.
