### PR TITLE
fix: rust static and shared library failing to find extern crate in windows-msvc

### LINKED ISSUE #6604: [Bug] fails to build rust's static library
### Xmake Version

xmake v3.0.0+HEAD.0db4fe610

### Operating System Version and Architecture

Windows 11 24H2

### Describe Bug

I tested it on an xmake rust's static project template but on compile it errors with `can't find crate for ``foo``;`.

I'm currently on rust:

```console
> rustc --version                                                                                                                                                          
rustc 1.88.0 (6b00bc388 2025-06-23)
```

### Expected Behavior

It should be able to compile and run.

### Project Configuration

```lua
target("foo")
    set_kind("static")
    add_files("src/foo.rs")

target("testing_demo")
    set_kind("binary")
    add_deps("foo")
    add_files("src/main.rs")
```

### Additional Information and Error Logs

```console
> xmake create -l rust -t static -P testing
create testing ...
  [+]: src\foo.rs
  [+]: src\main.rs
  [+]: xmake.lua
  [+]: .gitignore
create ok!

> cd testing
> xmake f -cvD
checking for platform ... windows                                                                                                                                          
checking for architecture ... x64                                                                                                                                          
checking for cl.exe ... D:\Dev\VisualStudio\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\bin\HostX64\x64\cl.exe
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.43.34810
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
checkinfo: cannot runv(nim.exe --version), No such file or directory
checking for nim ... no
configure
{
    builddir = build
    host = windows
    mode = release
    ndk_stdcxx = true
    kind = static
    plat = windows
    clean = true
    ccache = true
    arch = x64
    vs = 2022
}
```

on which it errors with `can't find crate for ``foo``;`.

```console
> xmake b -vD
checking for rustc ... D:\Dev\rust\.cargo\bin\rustc.exe                                                                                                                    
checking for the rust compiler (rc) ... rustc.exe                                                                                                                          
[ 31%]: linking.release foo.rlib
checking for rustc ... D:\Dev\rust\.cargo\bin\rustc.exe
checking for the rust static library archiver (rcar) ... rustc.exe
D:\Dev\rust\.cargo\bin\rustc.exe --target=x86_64-pc-windows-msvc --edition 2018 --crate-type=lib -o build\windows\x64\release\foo.rlib src\foo.rs
[ 79%]: linking.release testing_demo.exe
checking for rustc ... D:\Dev\rust\.cargo\bin\rustc.exe
checking for the rust linker (rcld) ... rustc.exe
D:\Dev\rust\.cargo\bin\rustc.exe --target=x86_64-pc-windows-msvc --edition 2018 -Lbuild\windows\x64\release --crate-type=bin -o build\windows\x64\release\testing_demo.exe src\main.rs
error: @programdir\core\main.lua:329: @programdir\actions\build\main.lua:146: @programdir\modules\async\runjobs.lua:331: @programdir\rules\rust\build\target.lua:67: @programdir\core\sandbox\modules\os.lua:273: error[E0463]: can't find crate for `foo`
 --> src\main.rs:1:1
  |
1 | extern crate foo;
  | ^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0463`.

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:1075]:
    [@programdir\core\sandbox\modules\os.lua:273]: in function 'runv'
    [@programdir\modules\core\tools\rustc.lua:129]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:246]:
    [@programdir\rules\rust\build\target.lua:67]: in function 'build_sourcefiles'
    [@programdir\rules\rust\build\target.lua:83]:
    [@programdir\modules\private\action\build\target.lua:172]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:247]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:246]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:117]: in function 'try'
    [@programdir\modules\async\runjobs.lua:230]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:406]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:1075: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:329: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:406: in function <@programdir\core\base\scheduler.lua:399>
```

### PR DESCRIPTION
**Pull request by IMXEren**
* Before adding new features and new modules, please go to issues to submit the relevant feature description first.
* Write good commit messages and use the same coding conventions as the rest of the project.
* Please commit code to dev branch and we will merge into master branch in feature
* Ensure your edited codes with four spaces instead of TAB.

------

* 增加新特性和新模块之前，请先到issues提交相关特性说明，经过讨论评估确认后，再进行相应的代码提交，避免做无用工作。
* 编写友好可读的提交信息，并使用与工程代码相同的代码规范，代码请用4个空格字符代替tab缩进。
* 请提交代码到dev分支，如果通过，我们会在特定时间合并到master分支上。
* 为了规范化提交日志的格式，commit消息，不要用中文，请用英文描述。

------

- Aims to fix #6604 
- Also, added shared library template for rust.

```lua
target("foo")
    set_kind("static")
    add_files("src/foo.rs")
    -- set_values("rust.cratetype", "staticlib")
    -- set_values("rust.cratetype", "cdylib")

target("test1_demo")
    set_kind("binary")
    add_deps("foo")
    add_files("src/main.rs")
```

```lua
target("foo")
    set_kind("shared")
    add_files("src/foo.rs")
    set_values("rust.cratename", "bar")

target("test2_demo")
    set_kind("binary")
    add_deps("foo")
    add_files("src/main.rs") -- extern crate bar as foo;

    -- Incase of dylib, rule("rust") on_config ensures libstd shared library is available when running
```

### CODE REVIEW

File: xmake/rules/utils/inherit_links/inherit_links.lua [hunk 1]
```diff
@@ -91,6 +91,16 @@ function main(target)
...
             _add_export_value(target, "includedirs", path.directory(targetfile))
         end
+
+        if target:rule("rust") then
+            local cratetype = target:values("rust.cratetype")
+            -- only bin, lib, rlib, dylib can make use of --extern CRATE[=PATH]
+            if cratetype ~= "staticlib" and cratetype ~= "cdylib" then
+                local cratename = target:values("rust.cratename") or target:name()
+                local extern_crate_opt = string.format('--extern %s=%s', cratename, target:targetfile())
+                _add_export_value(target, "rcldflags", extern_crate_opt)
```
Comment (waruqi) [inline xmake/rules/utils/inherit_links/inherit_links.lua]: we can use frameworks to export it.

https://github.com/xmake-io/xmake/blob/5929eeebf059979fd4a8952b74696a2c4ea33750/xmake/modules/core/tools/rustc.lua#L89

File: xmake/templates/rust/shared/project/xmake.lua [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+    add_deps("foo")
+    add_files("src/main.rs")
+
+    --- Make sure libstd shared library is available
+    before_run(function (target)
+        local outdata, errdata = os.iorun("rustc --print=sysroot")
+        assert(not errdata or errdata == "", "failed to find rust sysroot:\n" .. errdata)
+        local libstd = path.join(outdata:trim(), "bin")
+        os.addenvs({PATH = libstd, LD_LIBRARY_PATH = libstd, DYLD_LIBRARY_PATH = libstd})
+    end)
```
Comment (waruqi) [inline xmake/templates/rust/shared/project/xmake.lua]: Please don't add it here, we should make sure the example project is as simple as possible.

we should do it in rust rule.

File: xmake/templates/rust/shared/project/xmake.lua [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+    add_files("src/foo.rs")
+
+target("${TARGETNAME}_demo")
+    set_kind("binary")
+    add_deps("foo")
+    add_files("src/main.rs")
+
+    --- Make sure libstd shared library is available
+    before_run(function (target)
+        local outdata, errdata = os.iorun("rustc --print=sysroot")
```
Comment (waruqi) [inline xmake/templates/rust/shared/project/xmake.lua]: please use find_tool rustc + os.iorunv

File: xmake/templates/rust/shared/project/xmake.lua (hunk 2 above)
Comment (IMXEren) [reply xmake/templates/rust/shared/project/xmake.lua]: Yes, using the rule is a good idea — I hadn’t thought of that. Did it now.

File: xmake/rules/rust/xmake.lua [hunk 4]
```diff
@@ -81,6 +97,18 @@ rule("rust.build")
     end)
     on_build("build.target")
 
+    before_run(function (target)
+        import("lib.detect.find_tool")
+
+        -- Make sure libstd shared library is available
+        local rc = find_tool("rustc")
+        assert(rc, "rustc not found. Failed to add libstd in env")
+        local outdata, errdata = os.iorunv(rc.program, {"--print=sysroot"})
```
Comment (waruqi) [inline xmake/rules/rust/xmake.lua:106]: This will cause rustc to be executed once every `xmake run`. We should set runenvs in on_config.

see

https://xmake.io/api/description/project-target.html#add-runtime-environment-variables

File: xmake/rules/utils/inherit_links/inherit_links.lua [hunk 5]
```diff
@@ -91,6 +91,16 @@ function main(target)
...
             _add_export_value(target, "includedirs", path.directory(targetfile))
         end
+
+        if target:rule("rust") then
+            local cratetype = target:values("rust.cratetype")
+            -- only bin, lib, rlib, dylib can make use of --extern CRATE[=PATH]
+            if cratetype ~= "staticlib" and cratetype ~= "cdylib" then
+                local extern_crate_opt = rustc:nf_framework(target:targetfile())
+                local extern_crate = table.concat(extern_crate_opt, " ")
+                _add_export_value(target, "rcflags", extern_crate)
```
Comment (waruqi) [inline xmake/rules/utils/inherit_links/inherit_links.lua]: no, we should export frameworks. `_add_export_value(target, "frameworks", ...)`

File: xmake/rules/rust/xmake.lua (hunk 4 above)
Comment (IMXEren) [reply xmake/rules/rust/xmake.lua:106]: You are right, it'll just slow down `xmake r` even if the binary is statically linked. So, better do on_config.

File: xmake/rules/rust/xmake.lua [hunk 6]
```diff
@@ -81,6 +97,20 @@ rule("rust.build")
...
+
+        -- Ensure libstd shared library is available when running
+        local rc = find_tool("rustc")
+        assert(rc, "rustc not found. Failed to add libstd in env")
+        local outdata, errdata = os.iorunv(rc.program, {"--print=sysroot"})
+        assert(not errdata or errdata == "", "failed to find rust sysroot:\n" .. errdata)
+        local libstd = path.join(outdata:trim(), "bin")
+        target:add("runenvs", "PATH", libstd)
+        target:add("runenvs", "LD_LIBRARY_PATH", libstd)
+        target:add("runenvs", "DYLD_LIBRARY_PATH", libstd)
```
Comment (waruqi) [inline xmake/rules/rust/xmake.lua]: DYLD_LIBRARY_PATH doesn't seem to solve the problem of loading stdlib on macos.

If I change stdlib to lib directory. it will work.

```sh
ruki:shared_library ruki$ xmake r
dyld[11103]: Library not loaded: @rpath/libstd-556e5c085d373926.dylib
  Referenced from: <BB04D39D-5FAE-3E5D-B229-78DF4BC0D7ED> /Users/ruki/projects/personal/xmake/tests/projects/rust/shared_library/build/macosx/x86_64/release/t
est
  Reason: tried: '/Users/ruki/projects/personal/xmake/tests/projects/rust/shared_library/build/macosx/x86_64/release/libstd-556e5c085d373926.dylib' (no such f
ile), '/Users/ruki/projects/personal/xmake/tests/projects/rust/shared_library/build/macosx/x86_64/release/libstd-556e5c085d373926.dylib' (no such file)
error: execv(/Users/ruki/projects/personal/xmake/tests/projects/rust/shared_library/build/macosx/x86_64/release/test ) failed(-1)
```

File: xmake/rules/rust/xmake.lua [hunk 7]
```diff
@@ -97,16 +97,18 @@ rule("rust.build")
...
+    on_config(function (target)
         import("lib.detect.find_tool")
 
-        -- Make sure libstd shared library is available
+        -- Ensure libstd shared library is available when running
         local rc = find_tool("rustc")
         assert(rc, "rustc not found. Failed to add libstd in env")
         local outdata, errdata = os.iorunv(rc.program, {"--print=sysroot"})
         assert(not errdata or errdata == "", "failed to find rust sysroot:\n" .. errdata)
         local libstd = path.join(outdata:trim(), "bin")
```
Comment (waruqi) [inline xmake/rules/rust/xmake.lua]: stdlib is in the lib directiry on non-windows.

```console
$ ls -l /usr/local/Cellar/rust/1.66.0/lib
total 281760
-r--r--r--   1 ruki  staff  136790048  1 10  2023 librustc_driver-3b79dae3146d75e8.dylib
-r--r--r--   1 ruki  staff    6225640  1 10  2023 libstd-556e5c085d373926.dylib
-r--r--r--   1 ruki  staff    1240432  1 10  2023 libtest-61048579174a71f6.dylib
drwxr-xr-x  10 ruki  staff        320  1 10  2023 rustlib
```

File: xmake/rules/rust/xmake.lua [hunk 8]
```diff
@@ -97,16 +97,18 @@ rule("rust.build")
...
-        os.addenvs({PATH = libstd, LD_LIBRARY_PATH = libstd, DYLD_LIBRARY_PATH = libstd})
+        target:add("runenvs", "PATH", libstd)
```
Comment (waruqi) [inline xmake/rules/rust/xmake.lua]: We should not set these three variables at the same time, but should set them separately according to different systems.

```lua
if target:is_plat("windows") then
      -- add PATH
elseif target:is_plat("macosx") then
    -- DYLD_LIBRARY_PATH
else
    -- LD_LIBRARY_PATH
end
```
