### PR TITLE
fix(qt.qmltyperegistrar): Collect metatypes info

### LINKED ISSUE #6647: Build error if `qmltyperegistrar` input json-file is empty
### Xmake Version

v3.0.1+20250718

### Operating System Version and Architecture

macOS Sequoia 15.5 (arm64)

### Describe Bug

I have a simple Qt QML engine extension (aka `qt.qmlplugin`). Not all C++ files in it contain QML type definitions. This results in an error.

I add all `*.hpp` files via `add_files`. Due to that, they all are processed by the `qt.moc` rule. MOC generates empty files if nothing moc-relevant is found in the header. And then the generated files are passed into a `qmltyperegistrar` which throws an error.

### Expected Behavior

Everything should work.

### Project Configuration

```lua
target('myqmlplugin')
    set_values('qt.qmlplugin.import_name', 'myqmlplugin')
    add_rules('qt.qmlplugin')
    add_files('src/*.hpp', 'src/*.cpp')
```
However, some `*.hpp`-files contain no `QML_*` macros.

### Additional Information and Error Logs

```console
error: Error: build/.gens/myqmlplugin/macosx/arm64/release/extensions/myqmlplugin/src/moc_Clip.cpp.json:: Failed to parse JSON: 5 illegal value
```

### PR DESCRIPTION
**Pull request by GooRoo**
Instead of passing all JSON-files generated by MOC directly into `qmltyperegistrar`, combine them into a single JSON-file first using MOC.

Resolves #6647.

### CODE REVIEW

File: xmake/rules/qt/qmltyperegistrar/xmake.lua [hunk 1]
```diff
@@ -90,20 +94,29 @@ rule("qt.qmltyperegistrar")
...
+        batchcmds:vrunv(moc, table.join(moc_args, metatype_files))
+
+        -- gen sourcefile
         local args = {
             "--generate-qmltypes=" .. target:get("targetdir") .. "/plugin.qmltypes",
             "--import-name=" .. importname,
             "--major-version=" .. majorversion,
             "--minor-version=" .. minorversion,
-            "-o", sourcefile
+            "-o", sourcefile,
```
Comment (waruqi) [inline xmake/rules/qt/qmltyperegistrar/xmake.lua:115]: please use `path(sourcefile)` to wrap all file path, project generator will handle path better.

File: xmake/rules/qt/qmltyperegistrar/xmake.lua [hunk 2]
```diff
@@ -90,20 +94,29 @@ rule("qt.qmltyperegistrar")
...
             local sourcefile_moc = target:autogenfile(path.join(path.directory(mocedfile), filename_moc))
-            table.insert(metatypefiles, path(sourcefile_moc .. ".json"))
+            table.insert(metatype_files, path(sourcefile_moc .. ".json"))
         end
 
+        -- generate a common metatypes.json file
+        -- @see https://github.com/xmake-io/xmake/issues/6647
+        local moc_args = {
+            "--collect-json",
+            "-o", metatypesfile
```
Comment (waruqi) [inline xmake/rules/qt/qmltyperegistrar/xmake.lua:104]: and here

File: xmake/rules/qt/qmltyperegistrar/xmake.lua [hunk 3]
```diff
@@ -90,20 +94,29 @@ rule("qt.qmltyperegistrar")
...
+
+        -- gen sourcefile
         local args = {
             "--generate-qmltypes=" .. target:get("targetdir") .. "/plugin.qmltypes",
             "--import-name=" .. importname,
             "--major-version=" .. majorversion,
             "--minor-version=" .. minorversion,
-            "-o", sourcefile
+            "-o", sourcefile,
+            metatypesfile
```
Comment (waruqi) [inline xmake/rules/qt/qmltyperegistrar/xmake.lua:116]: and here

File: xmake/rules/qt/qmltyperegistrar/xmake.lua [hunk 4]
```diff
@@ -90,20 +94,29 @@ rule("qt.qmltyperegistrar")
                 filename_moc = basename .. ".moc"
             end
             local sourcefile_moc = target:autogenfile(path.join(path.directory(mocedfile), filename_moc))
-            table.insert(metatypefiles, path(sourcefile_moc .. ".json"))
+            table.insert(metatype_files, path(sourcefile_moc .. ".json"))
```
Comment (waruqi) [inline xmake/rules/qt/qmltyperegistrar/xmake.lua:97]: like this

File: xmake/rules/qt/qmltyperegistrar/xmake.lua (hunk 1 above)
Comment (GooRoo) [reply xmake/rules/qt/qmltyperegistrar/xmake.lua:115]: Wrapped in `path()` at the initialization.
