### PR TITLE
fix qt cross

### LINKED ISSUE #7381: 开发板 Qt 应用交叉编译时，find_qt里的qmake处理不当
### Xmake 版本

3.0.7

### 操作系统版本和架构

ubuntu 20.04

### 描述问题

第一个问题是：qt.conf文件和qmake在同一目录的情况下，`find_qt.lua`，额外引入了bin的一个问题

Image

如图这样修改，就可以正确找到qt.conf文件。至于我这里的qmake和qt.conf是不是规范摆放，就不得而知了，但希望xmake能够提供选项，或者更好的探测。

第二个问题是：当qmake的返回有使用了QT_SYSROOT时，后续的路径如`sdkdir`、`includedir`等等，都应该用上这个QT_SYSROOT？

Image

如图这样修改，是可以正确的找到qt相关的头文件，但这里的修改不够完整，后续的编译还会引发错误，所以提了此issue，希望能得到完整的修复。

手动调用qmake的返回如下：

Image

### 期待的结果

能正常的交叉编译

### 工程配置

xmake内置的qt widgetapp demo工程。

交叉编译配置如下：
```
"xmake.additionalConfigArguments": [
        "--sdk=/home/tronlong/RK3506/rk3506_linux6.1_release_v1.1.0/buildroot/output/rockchip_rk3506/host/usr",
        "--qt=/home/tronlong/RK3506/rk3506_linux6.1_release_v1.1.0/buildroot/output/rockchip_rk3506/host/bin"
        "--qt_host=/usr/lib/qt5/bin"
    ],
```

### 附加信息和错误日志

无

### PR DESCRIPTION
**Pull request by ThzShun**
fix #7381

- find_qt.lua
qt.conf may be in the same directory as qmake.
should be handle QT_SYSROOT

- qt/load.lua
'cross' plat did not handle it properly.

### CODE REVIEW

File: xmake/modules/detect/sdks/find_qt.lua [hunk 1]
```diff
@@ -288,6 +288,19 @@ function _find_qt(sdkdir, sdkver, sdkdir_host)
...
+    -- handle qt sysroot
+    if qtenvs.QT_SYSROOT and qtenvs.QT_SYSROOT ~= "" then
+        local qt_sysroot = qtenvs.QT_SYSROOT
+        sdkdir = qt_sysroot .. sdkdir
+        bindir = qt_sysroot .. bindir
+        libexecdir = qt_sysroot .. libexecdir
+        qmldir = qt_sysroot .. qmldir
+        libdir = qt_sysroot .. libdir
+        pluginsdir = qt_sysroot .. pluginsdir
+        includedir = qt_sysroot .. includedir
```
Comment (waruqi) [inline xmake/modules/detect/sdks/find_qt.lua]: Have you tested this in a non-cross-compilation environment? I currently don't have an environment available to test and verify it.

Comment (ThzShun) [reply xmake/modules/detect/sdks/find_qt.lua]: 930dbd98b5f4c789bf8b1e17a3068689
1b06026926f0bcd0baac31ce28c54c56

Compiling with local gcc on this machine works fine.

File: xmake/modules/detect/sdks/find_qt.lua [hunk 2]
```diff
@@ -288,6 +288,19 @@ function _find_qt(sdkdir, sdkver, sdkdir_host)
     local includedir = qtenvs.QT_INSTALL_HEADERS
     local mkspecsdir = qtenvs.QMAKE_MKSPECS or path.join(qtenvs.QT_HOST_DATA, "mkspecs")
     local mkspec = qtenvs.QMAKE_XSPEC or qtenvs.QMAKE_SPEC
+
+    -- handle qt sysroot
+    if qtenvs.QT_SYSROOT and qtenvs.QT_SYSROOT ~= "" then
+        local qt_sysroot = qtenvs.QT_SYSROOT
+        sdkdir = qt_sysroot .. sdkdir
```
Comment (waruqi) [inline xmake/modules/detect/sdks/find_qt.lua]: sdkdir may be an absolute path. We should implement some compatibility handling rather than simply concatenating directly.

and please use path.join instead of `..`

File: xmake/modules/detect/sdks/find_qt.lua [hunk 3]
```diff
@@ -288,6 +288,19 @@ function _find_qt(sdkdir, sdkver, sdkdir_host)
     local includedir = qtenvs.QT_INSTALL_HEADERS
     local mkspecsdir = qtenvs.QMAKE_MKSPECS or path.join(qtenvs.QT_HOST_DATA, "mkspecs")
     local mkspec = qtenvs.QMAKE_XSPEC or qtenvs.QMAKE_SPEC
+
+    -- handle qt sysroot
+    if qtenvs.QT_SYSROOT and qtenvs.QT_SYSROOT ~= "" then
```
Comment (waruqi) [inline xmake/modules/detect/sdks/find_qt.lua]:
```lua
local sysroot = qtenvs.QT_SYSROOT or ""
if #sysroot > 0 and path.isdir(sysroot) then
end
```

File: xmake/modules/detect/sdks/find_qt.lua [hunk 4]
```diff
@@ -208,8 +208,8 @@ function _get_qtenvs(qmake, sdkdir)
     local results
 
     -- Try with -qtconf first if sdkdir is provided
-    if sdkdir then
-        local conf_paths = {path.join(sdkdir, "bin", "target_qt.conf"), path.join(sdkdir, "bin", "qt.conf")}
+    if sdkdir then
```
Comment (waruqi) [inline xmake/modules/detect/sdks/find_qt.lua]: 行尾的空格删了

File: xmake/modules/detect/sdks/find_qt.lua [hunk 5]
```diff
@@ -209,7 +209,7 @@ function _get_qtenvs(qmake, sdkdir)
 
     -- Try with -qtconf first if sdkdir is provided
     if sdkdir then
-        local conf_paths = {path.join(sdkdir, "bin", "target_qt.conf"), path.join(sdkdir, "bin", "qt.conf")}
+        local conf_paths = {path.join(sdkdir, "bin", "target_qt.conf"), path.join(sdkdir, "bin", "qt.conf"), path.join(sdkdir, "qt.conf")}
```
Comment (waruqi) [inline xmake/modules/detect/sdks/find_qt.lua]: 还有这后面的空格
